export const ADD_TODO = 'ADD_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const SET_FILTER = 'SET_FILTER'
export const ADD_COUNTER = 'ADD_COUNTER'
export const MINUS_COUNTER = 'MINUS_COUNTER'
export const SET_INPUT_VALUE = 'SET_INPUT_VALUE'
